server:
  port: 8080
  
# nohup java -jar -Dspring.profiles.active=prod myworkspace-0.0.1-SNAPSHOT.jar > myworkspace.log &
# ./gradlew build && java -jar build/libs/myworkspace-0.0.1-SNAPSHOT.jar

spring:
  application:
    name: foodrecipe
  profiles:    active: default
  servlet:
  #multipart 파일처리 조건
    multipart:      max-file-size: -1      max-request-size: -1
  #database 접속 정보
  datasource:
         #jdbc:mysql://엔드포인트/데이터베이스?옵션...    url: jdbc:mysql://mysql-1.cukreghkczhr.ap-northeast-2.rds.amazonaws.com/mypageservice?useUnicode=true&characterEncoding=utf-8
    
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    show-sql: true # 데이터처리할 대 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 데이터베이스 객체 생성    

  rabbitmq:
    host: ec2-3-34-127-170.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123
    
cloud:
  aws:
    credentials:
      accessKey: AKIAIRP7SQLQUEJKPVEA
      secretKey: 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
---    
cloud:
  aws:
    s3:
      bucket: recipeimage-myservice
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

api:
  base-path: http://localhost:8080
  
  
---
spring:
  profiles: prod 
  redis:
    host: 54.180.141.248
    port: 6379
    password: foobared
  
api:
 base-path: http://ec2-3-34-127-170.ap-northeast-2.compute.amazonaws.com:8080

