server:
  port: 8080
  
# nohup java -jar -Dspring.profiles.active=prod mypageservice-0.0.1-SNAPSHOT.jar > mypageservice.log &
# ./gradlew build && java -jar build/libs/myworkspace-0.0.1-SNAPSHOT.jar

spring:
  application:
    name: mypage
  profiles:    active: default
  servlet:
  #multipart 파일처리 조건
    multipart:      max-file-size: -1      max-request-size: -1
  #database 접속 정보
  datasource:
         #jdbc:mysql://엔드포인트/데이터베이스?옵션...    url: jdbc:mysql://mysql-1.cqv7z5i3ztkr.ap-northeast-2.rds.amazonaws.com/mypageservice?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    show-sql: true # 데이터처리할 대 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 데이터베이스 객체 생성   
#    properties:
#     hibernate: generate_statistics=true 
  redis:
    host: 15.164.171.148
    port: 6379  
    password: foobared
   
  rabbitmq:
    host: ec2-13-125-229-154.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123
    

  api:
    base-path: http://192.168.0.29:8080
eureka:
  client:
    service-url:
      # 유레카 서버의 주소를 작성
      # 유레카 설치된 ec2 ip 주소:8761/eureka/
      defaultZone: http://3.36.141.39:8761/eureka/
  instance:
      # 본인 서비스의 ec2 ip 주소
    hostname: 15.164.171.148  
  
---
spring:
  profiles: prod 
  redis:
    host: 15.164.171.148
    port: 6379
    password: foobared
  api:
    base-path: http://13.209.41.162:8080
    
eureka:
  client:
    service-url:
      # 유레카 서버의 주소를 작성
      # 유레카 설치된 ec2 ip 주소:8761/eureka/
      defaultZone: http://3.36.141.39:8761/eureka/
  instance:
      # 본인 서비스의 ec2 ip 주소
    hostname: 15.164.171.148
      
  



# 클라이언트 부하 분산 활성화
ribbon:
  eureka:
    enabled: true
